Models/Appointment.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace DocApp.Models
{
    public class Appointment : BaseEntity
    {
        public enum StatusEnum
        {
            Pending,
            Active,
            Closed
        }

        public string DoctorName { get; set; } = string.Empty;
        public string PatientName { get; set; } = string.Empty;
        public string PatientPhone { get; set; } = string.Empty;
        public string PatientEmail { get; set; } = string.Empty;

        public string SlotNo { get; set; } = string.Empty;
        public DateTime Date { get; set; }
        public StatusEnum Status { get; set; }
        public int Age { get; set; }

        public string Disease { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string? Prescription { get; set; }

        // Foreign key property
        [ForeignKey("PatientId")]
        public Guid PatientId { get; set; }
    }
}

Controllers/AppointmentsController.cs
using DocApp.Data;
using DocApp.GenericRepository;
using DocApp.Models;
using DocApp.Services.AppointmentService;
using DocApp.Services.UserService;
using DocApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Drawing.Printing;
using System.Text;
using X.PagedList;

namespace DocApp.Controllers
{
    public class AppointmentsController : Controller
    {
        private readonly IAppointmentService _appointments;
        private readonly IUserService _users;

        public AppointmentsController(IAppointmentService appointments, IUserService users)
        {
            _appointments = appointments;
            _users = users;
        }

        // GET: Appointment List
        [Authorize(Roles = "Staff , Patient")]
        public IActionResult AppointmentList(int? page)
        {
            var _apointmentList = _appointments.GetAll();

            int pageSize = 1;
            int pageNumber = (page ?? 1);

            return View(_apointmentList.ToPagedList(pageNumber, pageSize));
        }

        // GET: My Appointment List
        [Authorize(Roles = "Patient")]
        public IActionResult MyAppointmentList(int? page)
        {
            // Get the current user's ID from the session
            byte[]? userIdBytes;
            if (!HttpContext.Session.TryGetValue("UserId", out userIdBytes))
            {
                return RedirectToAction("Login", "Users");
            }
            Guid _currentUserId = new Guid(Encoding.ASCII.GetString(userIdBytes));

            var _myApointmentList = _appointments.GetAll().Where(a => a.PatientId == _currentUserId);

            int pageSize = 1;
            int pageNumber = (page ?? 1);

            return View(_myApointmentList.ToPagedList(pageNumber, pageSize));
        }

        // GET: Active Appointment List
        [Authorize(Roles = "Doctor")]
        public IActionResult ActiveAppointmentList(int? page)
        {
            var _activeApointmentList = _appointments.GetAll().Where(a => a.isActive == true );

            int pageSize = 1;
            int pageNumber = (page ?? 1);

            return View(_activeApointmentList.ToPagedList(pageNumber, pageSize));
        }

        // GET: Patient Details
        [Authorize(Roles = "Doctor")]
        public IActionResult PatientDetails(string Id)
        {
            var _patientDetails = _appointments.GetById(new Guid(Id));
            return View(_patientDetails);
        }

        // GET: Patient History
        [Authorize(Roles = "Doctor")]
        public IActionResult PatientHistory(string Id)
        {
            var _patientHistory = _appointments.GetAll().Where(a => a.PatientId == new Guid(Id));
            return View(_patientHistory);
        }

        // GET: Add Appointment
        [Authorize(Roles = "Patient")]
        public IActionResult AddAppointment()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Patient")]
        public IActionResult AddAppointment(PatientVM model)
        {
            // Get the current user's ID from the session
            byte[]? userIdBytes;
            if (!HttpContext.Session.TryGetValue("UserId", out userIdBytes))
            {
                return RedirectToAction("Login", "Users");
            }

            Guid userId = new Guid(Encoding.ASCII.GetString(userIdBytes));

            var _patient = _users.GetById(userId);

            //Cheeck if there is any active appointment
            var _apointment = _appointments.GetAll().Any(e => e.PatientId == userId && e.isActive == true);
            
            if (_apointment)
            {
                TempData["error"] = "You already have an active appointment";
                return RedirectToAction("AddAppointment");
            }

            var appointment = new Appointment
            {
                Id = Guid.NewGuid(),
                PatientId = _patient.Id,
                PatientName = model.FName + model.LName,
                Age = CalculateAge(DateTime.Parse(_patient.DOB)),

                PatientPhone = _patient.Phoneno,
                PatientEmail = _patient.Email,

                Disease = model.Disease,
                Description = model.Description,

                SlotNo = model.SlotNo,
                Date = DateTime.Now,
                Status = Appointment.StatusEnum.Pending,
                isActive = false
            };
             
            _appointments.Add(appointment);
            _appointments.SaveChanges();

            TempData["success"] = "Appointment Created successfully";
            return RedirectToAction("MyAppointmentList");

        }

        // Method to calculate age based on date of birth
        private int CalculateAge(DateTime dob)
        {
            var age = DateTime.Now.Year - dob.Year;
            
            //if the person's birthdy has not been arrived subtract current year
            if (DateTime.Now < dob.AddYears(age))
            {
                age--;
            }
            return age;
        }

        //GET: Appointments/Approved/Id
        [Authorize(Roles = "Doctor")]
        public IActionResult AddPrescription(Appointment model)
        {
            // Get the current user's ID from the session
            byte[]? userIdBytes;
            if (!HttpContext.Session.TryGetValue("UserId", out userIdBytes))
            {
                return RedirectToAction("Login", "Users");
            }
            Guid userId = new Guid(Encoding.ASCII.GetString(userIdBytes));
            var _currentUser = _users.GetById(userId);

            var _appointment = _appointments.GetById(model.Id);

            if (_appointment != null)
            {
                _appointment.DoctorName = _currentUser.FName+_currentUser.LName;

                if(_appointment.Prescription == null)
                {
                    _appointment.Prescription = model.Prescription;
                    TempData["success"] = "Prescription added successfully";
                }
                else
                {
                    _appointment.Prescription = model.Prescription;
                    TempData["success"] = "Prescription Updated successfully";
                }
            }
            else
            {
                TempData["error"] = "Unable to Add prescription";
            }
            
            _appointments.SaveChanges();

            return RedirectToAction("ActiveAppointmentList");
        }

        //GET: Appointments/Approved/Id
        [Authorize(Roles = "Staff")]
        public IActionResult Active(string Id)
        {
            if (Id == null || !AppointmentExists(Id))
            {
                return NotFound();
            }

            var _appointment = _appointments.GetById(new Guid(Id));

            if (_appointment != null)
            {
                _appointment.Status = Appointment.StatusEnum.Active;
                _appointment.isActive = true;
                TempData["success"] = "Appointment Activated successfully";
            }
            else
            {
                TempData["error"] = "Unable to find the Appointment.";
            }

            _appointments.SaveChanges();

            return RedirectToAction("AppointmentList");
        }

        //GET: Appointments/Rejected/Id
        [Authorize(Roles = "Doctor , Staff")]
        public IActionResult Closed(string Id)
        {
            if (Id == null || !AppointmentExists(Id))
            {
                return NotFound();
            }

            var _appointment = _appointments.GetById(new Guid(Id));

            if (_appointment != null)
            {
                _appointment.Status = Appointment.StatusEnum.Closed;
                _appointment.isActive = false;
                TempData["success"] = "Appointment Closed successfully";
            }
            else
            {
                TempData["error"] = "Unable to find the Appointment.";
            }

            _appointments.SaveChanges();

            // Get the current user's ID from the session
            byte[]? userIdBytes;
            if (!HttpContext.Session.TryGetValue("UserId", out userIdBytes))
            {
                return RedirectToAction("Login", "Users");
            }
            Guid userId = new Guid(Encoding.ASCII.GetString(userIdBytes));
            var _currentUser = _users.GetById(userId);
            
            if(_currentUser.UserType == "Doctor")
            {
                TempData["success"] = "Appointment Closed successfully";
                return RedirectToAction("ActiveAppointmentList");
            }

            return RedirectToAction("AppointmentList");
        }

        //GET: Appointments/Delete/Id
        [Authorize(Roles = "Doctor , Staff , Patient")]
        public IActionResult Delete(string Id)
        {
            if (Id == null || !AppointmentExists(Id))
            {
                return NotFound();
            }

            var _appointment = _appointments.GetById(new Guid(Id));

            // Get the current user's ID from the session
            byte[]? userIdBytes;
            if (!HttpContext.Session.TryGetValue("UserId", out userIdBytes))
            {
                return RedirectToAction("Login", "Users");
            }
            Guid userId = new Guid(Encoding.ASCII.GetString(userIdBytes));
            var _currentUser = _users.GetById(userId);

            if (_currentUser.UserType =="Patient" && _appointment.PatientId != _currentUser.Id) 
            {
                TempData["error"] = "You can only delete your own Appointment!";
                return RedirectToAction("MyAppointmentList");
            }
            else if (_currentUser.UserType == "Doctor") 
            {
                TempData["success"] = "Appointment deleted successfully";

Views/Appointments/MyAppointmentList.cshtml
@model X.PagedList.IPagedList<DocApp.Models.Appointment>
@using System.Security.Claims;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;

@{
    ViewData["Title"] = "My Appointments";
}

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Dashboard /</span>My Appointments</h4>

    <!-- Bordered Table -->
    
    <partial name="_Alerts" />

    <div class="card">
        <h5 class="card-header">My Appointments</h5>
        <div class="card-body">
            <div class="table-responsive text-nowrap">
                <table id="booking-table" class="table" style="width:100%">
                    <thead>

                        <tr>
                            <th>No</th>
                            <th>Doctor</th>
                            <th>SlotNo</th>
                            <th>Apponiment Date</th>
                            <th>Status</th>
                            <th>Disease</th>
                            <th>Description</th>
                            <th>Prescription</th>
                            <th>Actions</th>
                        </tr>

                    </thead>
                    <tbody>
                        @{
                            int counter = 1;
                        }
                        @foreach (var appointment in Model)
                        {
                            <tr>
                                <td>@counter</td>
                                <td>@appointment.DoctorName</td>
                                <td>@appointment.SlotNo</td>
                                <td>@appointment.Date.ToShortDateString()</td>
                                <td>
                                    @if (appointment.Status == Appointment.StatusEnum.Pending)
                                    {
                                        <span class="badge bg-label-info me-1">Pending</span>
                                    }
                                    else if (appointment.Status == Appointment.StatusEnum.Active)
                                    {
                                        <span class="badge bg-label-success me-1">Active</span>
                                    }
                                    else
                                    {
                                        <span class="badge bg-label-danger me-1">Closed</span>
                                    }
                                </td>
                                <td>@appointment.Disease</td>
                                <td style="white-space: normal; word-wrap: break-word; max-width: 150px;">@appointment.Description</td>
                                <td style="white-space: normal; word-wrap: break-word; max-width: 150px;">@appointment.Prescription</td>
                                <td>
                                    <div class="d-flex justify-content-around">
                                        
                                        <a href="/Appointments/Delete?Id=@appointment.Id" class="btn btn-icon btn-sm btn-outline-danger"
                                           data-bs-toggle="tooltip"
                                           data-bs-offset="0,4"
                                           data-bs-placement="top"
                                           data-bs-html="true"
                                           title=""
                                           data-bs-original-title="<i class='bx bx-trash bx-xs'></i> <span>Delete</span>">
                                            <span class="tf-icons bx bx-trash"></span>
                                        </a>
                                        
                                    </div>
                                </td>
                            </tr>
                            counter++;
                        }
                    </tbody>
                </table>

                <!-- Render pagination controls -->
                <div class="pagination-container">
                    @Html.PagedListPager(Model, page => Url.Action("MyAppointmentList", new { page }), new PagedListRenderOptions() {
                    LiElementClasses = new[] { "page-item" },
                    PageClasses = new[] { "page-link" },
                    UlElementClasses = new[] { "pagination" },
                    DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                    DisplayLinkToLastPage = PagedListDisplayMode.Always
                    })
                </div>

            </div>
        </div>
    </div>
    <!--/ Bordered Table -->
    
</div>

@section scripts {
    <script src="https://cdn.datatables.net/1.11.0/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" type="text/javascript"></script>
    @*<script src="https://cdn.datatables.net/buttons/2.0.0/js/dataTables.buttons.min.js" type="text/javascript"></script>*@
    <script src="https://cdn.datatables.net/buttons/2.0.0/js/buttons.html5.min.js" type="text/javascript"></script>

@*    <script src="~/assets/js/datatables_pdf/pdfmake.min.js"></script>
    <script src="~/assets/js/datatables_pdf/vfs_fonts.js"></script>*@

    <script>

        $(document).ready(function () {
            $('#booking-table').DataTable({
                "scrollY": "70vh",
                "scrollCollapse": true,
                "scrollX": "auto",
                "pageLength": -1,

                dom: 'Blfti',
                lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                
            });

        });

    </script>
}

Views/Appointments/PatientDetails.cshtml
@model DocApp.Models.Appointment
@using System.Security.Claims

@{
    ViewData["Title"] = "Details";
}

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Dashboard / Appointments</span> / Details</h4>

    <partial name="_Alerts" />

    <!-- Basic Layout -->
    <div class="row">
        
        <div class="col-xl-1"></div>

        <!-- Residence Details form-->
        <div class="col-xl-10">
            <div class="card mb-4">
                <div class="card-header d-flex">
                    <h5 class="mx-auto my-3"><strong class="fon">Patient Details</strong></h5>
                    
                </div>
                <div class="card-body">
                    <div class="row">

                        <div class="col-md-1"></div>

                        <div class="col-md-4 border border-top-0 rounded-bottom">
                            <!--About Section-->
                            <div class="text-muted fw-light">
                                About Patient
                                <hr />
                            </div>

                            <div class="mb-3">
                                <!--Basic Information-->
                                <div class="fw-bold">Basic Information</div>
                                <div class="row">

                                    <div class="col-sm-3">Name:</div>
                                    <div class="col-sm-9">@Model.PatientName</div>

                                    <div class="col-sm-3">Age:</div>
                                    <div class="col-sm-9">@Model.Age</div>

                                    <div class="col-sm-3">Slot:</div>
                                    <div class="col-sm-9">@Model.SlotNo</div>

                                </div>

                                <!--Contact Information-->
                                <div class="fw-bold mt-2">Contact Information</div>
                                <div class="row">

                                    <div class="col-sm-3">Phone:</div>
                                    <div class="col-sm-9 mb-1">@Model.PatientPhone</div>

                                    <div class="col-sm-3">Email:</div>
                                    <div class="col-sm-9 mb-1">@Model.PatientEmail</div>

                                </div>

                                <!--Buttons-->
                                <div class="d-flex btn-group justify-content-center m-4">

                                    <a class="btn btn-danger" href="/Appointments/Closed?Id=@Model.Id">
                                        <span class="tf-icons bx bx-x-circle"></span>&nbsp;Close
                                    </a>

                                    <a asp-controller="Appointments" asp-action="ActiveAppointmentList" class="btn btn-outline-secondary">
                                        <span class="tf-icons bx bx-right-arrow-alt"></span>&nbsp;Back
                                    </a>
                                </div>
                            </div>


                        </div>

                        <div class="col-md-1"></div>

                        <div class="col-md-5 border border-top-0 rounded-bottom">
                            <!--About Section-->
                            <div class="text-muted fw-light">
                                Patient Health
                                <hr />
                            </div>

                            <div class="row">

                                <!--Disease-->
                                <div class="col-sm-3">Disease:</div>
                                <div class="col-sm-9 mb-1">@Model.Disease</div>

                                <!--Description-->
                                <div class="col-sm-4 mt-2">Description:</div>
                                <div class="col-sm-8"></div>

                                <div class="col-sm-3"></div>
                                <div class="col-sm-9">

                                    @if (Model.Description != null)
                                    {
                                        @Model.Description
                                    }
                                    else
                                    {
                                        <p>No Description Provided.</p>
                                    }
                                </div>

                                <!--Prescription-->
                                <div class="col-sm-4 mt-2">Prescription:</div>
                                <div class="col-sm-8"></div>

                                <div class="col-sm-3"></div>
                                <div class="col-sm-9">

                                    @if (Model.Prescription != null)
                                    {
                                        @Model.Prescription

                                        <button type="button" class="btn btn-warning m-4" data-bs-toggle="modal" data-bs-target="#prescriptionModal">
                                            <span class="tf-icons bx bx-edit"></span>&nbsp;Edit Prescription
                                        </button>
                                    }
                                    else
                                    {
                                        <p>No Prescription added yet.</p>

                                        <button type="button" class="btn btn-primary m-4" data-bs-toggle="modal" data-bs-target="#prescriptionModal">
                                            <span class="tf-icons bx bx-book-add"></span>&nbsp;Add Prescription
                                        </button>
                                    }

                                </div>

                            </div>

                        </div>

                        <div class="col-md-1"></div>

                    </div>
                    
                </div>
            </div>
        </div>
        
        <div class="col-xl-1"></div>
    </div>
</div>

<!--Modal for Adding Prescription-->
<div class="modal fade" id="prescriptionModal" tabindex="-1" style="display: none;" aria-hidden="true" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">

            <!--Modal Header-->
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel2">Add Prescription</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form asp-action="AddPrescription" id="sub" method="post">
                
                <!--Modal Body-->
                <div class="modal-body">

                    <div class="row">
                        <input type="hidden" asp-for="@Model.Id" />
                        <div class="col mb-3">
                            <label class="form-label" asp-for="Prescription"></label>
                            <div class="input-group input-group-merge">
                                <span id="basic-icon-default-message2" class="input-group-text">
                                    <i class='bx bxs-detail'></i>
                                </span>
                                <textarea id="Prescription"
                                          class="form-control"
                                          asp-for="Prescription"
                                          placeholder="@(Model.Prescription != null ? Model.Prescription : "Write a prescription about this patient...")"
                                          aria-label="Write a prescription about this patient..."
                                          aria-describedby="basic-icon-default-Prescription"></textarea>

                            </div>
                            <span asp-validation-for="Prescription" class="text-danger"></span>
                        </div>
                    </div>

                </div>

                <!--Modal Footer-->
                <div class="modal-footer btn-group">
                    <button type ="submit" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                    
                    @if (Model.Prescription == null)
                    {
                        <button class="btn btn-primary">Add</button>
                    }
                    else
                    {
                        <button class="btn btn-warning">Edit</button>
                    }
                    
                </div>

            </form>
            
        </div>
    </div>
</div>

Views/Appointments/PatientHistory.cshtml
@model X.PagedList.IPagedList<DocApp.Models.Appointment>
@using System.Security.Claims;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;

@{
    ViewData["Title"] = "Appointment History";
}

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Dashboard / Appointments </span>/ Appointment History</h4>

    <!-- Bordered Table -->
    
    <partial name="_Alerts" />

    <div class="card">

        <div class="d-flex justify-content-between">
            @{
                bool isFirst = true;
                foreach (var appointment in Model)
                {
                    if (isFirst)
                    {
                        <h5 class="card-header">@appointment.PatientName's Appointment History</h5>
                        isFirst = false;
                    }

                }
            }

            <a asp-controller="Appointments" asp-action="ActiveAppointmentList" class="btn btn-outline-secondary m-4">
                <span class="tf-icons bx bx-right-arrow-alt"></span>&nbsp;Back
            </a>
        </div>
        

        <div class="card-body">
            <div class="table-responsive text-nowrap">
                <table id="booking-table" class="table" style="width:100%">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Doctor</th>
                            <th>SlotNo</th>
                            <th>Appointment Date</th>
                            <th>Status</th>
                            <th>Disease</th>
                            <th>Description</th>
                            <th>Prescription</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int counter = 1;
                        }
                        @foreach (var appointment in Model)
                        {
                            <tr>
                                <td>@counter</td>
                                <td>@appointment.DoctorName</td>
                                <td>@appointment.SlotNo</td>
                                <td>@appointment.Date.ToShortDateString()</td>
                                <td>
                                    @if (appointment.Status == Appointment.StatusEnum.Pending)
                                    {
                                        <span class="badge bg-label-info me-1">Pending</span>
                                    }
                                    else if (appointment.Status == Appointment.StatusEnum.Active)
                                    {
                                        <span class="badge bg-label-success me-1">Active</span>
                                    }
                                    else
                                    {
                                        <span class="badge bg-label-danger me-1">Closed</span>
                                    }
                                </td>
                                <td>@appointment.Disease</td>
                                <td style="white-space: normal; word-wrap: break-word; max-width: 150px;">@appointment.Description</td>
                                <td style="white-space: normal; word-wrap: break-word; max-width: 150px;">@appointment.Prescription</td>
                            </tr>
                            counter++;
                        }
                    </tbody>
                </table>

                <!-- Render pagination controls -->
                <div class="pagination-container">
                    @Html.PagedListPager(Model, page => Url.Action("PatientHistory", new { page }), new PagedListRenderOptions() {
                    LiElementClasses = new[] { "page-item" },
                    PageClasses = new[] { "page-link" },
                    UlElementClasses = new[] { "pagination" },
                    DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                    DisplayLinkToLastPage = PagedListDisplayMode.Always
                    })
                </div>

            </div>
        </div>
    </div>
    <!--/ Bordered Table -->
    
</div>

@section scripts {
    <script src="https://cdn.datatables.net/1.11.0/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" type="text/javascript"></script>
    @*<script src="https://cdn.datatables.net/buttons/2.0.0/js/dataTables.buttons.min.js" type="text/javascript"></script>*@
    <script src="https://cdn.datatables.net/buttons/2.0.0/js/buttons.html5.min.js" type="text/javascript"></script>

@*    <script src="~/assets/js/datatables_pdf/pdfmake.min.js"></script>
    <script src="~/assets/js/datatables_pdf/vfs_fonts.js"></script>*@

    <script>

        $(document).ready(function () {
            $('#booking-table').DataTable({
                "scrollY": "70vh",
                "scrollCollapse": true,
                "scrollX": "auto",
                "pageLength": -1,

                dom: 'Blfti',
                lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                
            });

        });


    </script>
}